# Generated by Django 2.2.7 on 2019-11-06 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20191106_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='prtub_date',
            new_name='pub_date',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='quesstion_text',
            new_name='question_text',
        ),
    ]
